// /** @type {import("next").Metadata} */
// import { Metadata } from 'next'
import Head from 'next/head'
// export const metadata: Metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <meta name="description" content="Description" />
      </Head>
      <body>{children}</body>
    </html>
  )
}
